### ISSUE TITLE
Fails to compile

### ISSUE THREAD

**Issue by FabianInostroza** [ARMmbed/cordio-ble-x-nucleo-idb0xa1#11]
Compilation fails with the following error:
```
[Error] BlueNrgHCIDriver.cpp@135,17: 'set_random_static_address' was not declared in this scope; did you mean 'get_random_static_address'?
[DEBUG] Return: 1
[DEBUG] Output: ./cordio-ble-x-nucleo-idb0xa1/BlueNrgHCIDriver.cpp: In member function 'virtual void ble::vendor::bluenrg::HCIDriver::handle_reset_sequence(uint8_t*)':
[DEBUG] Output: ./cordio-ble-x-nucleo-idb0xa1/BlueNrgHCIDriver.cpp:135:17: error: 'set_random_static_address' was not declared in this scope; did you mean 'get_random_static_address'?
[DEBUG] Output:   135 |                 set_random_static_address(pMsg);
[DEBUG] Output:       |                 ^~~~~~~~~~~~~~~~~~~~~~~~~
[DEBUG] Output:       |                 get_random_static_address
```

The method was added in a 6.0.0 PR (#12321) but the readme says this library should be used on mbed-os 5

**Comment by pan-** [comment]
@FabianInostroza Could you detail the issue ? Is this component not working with Mbed Os 5 ?

**Comment by FabianInostroza** [comment]
Hi @pan-,
The current head of master branch doesn't compile under mbed-os-5.15 because commit 02c14fb1de71aee263b213cc4928cebcea94faae replaced some calls to methods only available on mbed-os-6.

I tried the commit before that (f0555502bb4225eeaabce332d3b65a64a643dae1) and it compiles and at least the heartbeat example works.

PD: It would be nice if documentation of the idb0xa1 on mbed mentioned this library because the other one (ble-x-nucleo-idb0xa1) also doesn't compile on mbed-os-5.15 and seems harder to get it working (lots of error on missing and duplicated definitions).

> @FabianInostroza Could you detail the issue ? Is this component not working with Mbed Os 5 ?
